name:                rada-git
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/rada-git#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - interpolatedstring-perl6
  - optparse-applicative
  - text
  - QuickCheck
  - hspec

executables:
  rada-git:
    ghc-options: -Wall -Werror
    source-dirs:      src
    main:             Main.hs
