name:                rada-git
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/rada-git#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - QuickCheck
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - data-default
  - directory
  - exceptions
  - feed
  - groom
  - hspec
  - http-client
  - http-types
  - iconv
  - interpolatedstring-perl6
  - lens
  - network-uri
  - network-uri-json
  - optparse-applicative
  - path
  - path-io
  - string-class
  - text
  - xml-conduit
  - xml-types
  - wreq

executables:
  rada-git:
    ghc-options: -Wall -Werror
    source-dirs:      src
    main:             Main.hs
